name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build ijzer
      run: cargo build --verbose
      working-directory: ./ijzer
    - name: Run tests ijzer
      run: cargo test --verbose
      working-directory: ./ijzer
    - name: Build macro
      run: cargo build --verbose
      working-directory: ./ijzer_macro
    - name: Run tests macros
      run: cargo test --verbose
      working-directory: ./ijzer_macro
